### ISSUE TITLE
Consumer can't receive any message After a period of time runing,and Duration is not Determined

### ISSUE THREAD

**Issue by wp3xpp** [nsqio/go-nsq#157]
Consumer can't receive any message After a period of time runing,and Duration is not Determined
and the code in https://github.com/dlutxx/hiapns
i need help
thank u

**Comment by mreiferson** [comment]
@wp3xpp do you have any logs and how are you running the various services?

**Comment by wp3xpp** [comment]
When the program receives messages will be recorded in the local
The program will not report any mistakes
but can't receive any message After a period of time runing

**Comment by wp3xpp** [comment]
How can i judge the Connection with nsqd is ok？

**Comment by wp3xpp** [comment]
the code is very simple:
``` go
func FeedWorkerWithNSQ(worker *Worker, nsqTopic, nsqChannel, nsqdAddr string) (*nsq.Consumer, error) {
	nsqcfg := nsq.NewConfig()
	csm, err := nsq.NewConsumer(nsqTopic, nsqChannel, nsqcfg)
	if err != nil {
		return csm, err
	}

	csm.AddHandler(nsq.HandlerFunc(func(msg *nsq.Message) error {
		req, err := ParseRequestFromJSON(msg.Body)
		log.Println("Recv: ", string(msg.Body))
		if err == nil {
			worker.ReqCh <- req
		} else {
			log.Println("ERR:", err)
		}
		msg.Finish()
		return nil
	}))

	return csm, csm.ConnectToNSQD(nsqdAddr)
}
```

**Comment by wp3xpp** [comment]
you can see it will log the receive message :log.Println("Recv: ", string(msg.Body))
but it will print any message after a period of time

**Comment by wp3xpp** [comment]
what make consumer blocked on processing?

**Comment by jehiah** [comment]
@wp3xpp You are likely getting blocked in your handler on 

```go
worker.ReqCh <- req
```

You should investigate if something can block the [Worker.runLoop](https://github.com/dlutxx/hiapns/blob/master/worker.go#L26-L30) , and attempt to timeout the write onto `ReqCh`, or switch to a nonblocking channel write.

```go
select {
case worker.ReqCh <- req:
    return nil
case time.After(time.Second):
    return errors.New("unable to process message")
}
```

Also note, that you don't need to explicitly call `msg.Finish()` in your handler. Returning `nil` or `error` from the handler will allow go-nsq to do the right thing.

I'm going to close this issue as there isn't anything to indicate a go-nsq issue. If you have logs from nsqd and your consumer that indicate there might be a go-nsq issue please update this thread.

**Comment by wp3xpp** [comment]
thank u very much @jehiah
