### ISSUE TITLE
Please clarify relationship of go-nsq v1.0.4 to nsq release v0.3.5 and legacy/refactored API

### ISSUE THREAD

**Issue by glycerine** [nsqio/go-nsq#159]
The go-nsq README.md indicates:

The latest stable release is 1.0.4

NOTE: The public API has been refactored as of v1.0.0 and is not backwards compatible with previous releases. 0.3.7 is the last stable release compatible with the legacy API. Please read the UPGRADING guide.

Q1 - With respect to this (0.3.7 and 1.0.4) versioning scheme for go-nsq, are these versions only with respect to go-nsq, and independent of the nsq version?

Q2 - Does the go-nsq version with the refactored 1.0.4 API require a particular matched version of nsq to run against? Do I need to be running against a partciular minimum version of nsq?

Q3 - Are the HEAD of the git repos for nsq and go-nsq in sync with each other? e.g. if I submit a PR against one, should I be checking it against the other as of the latest code.

Thank you.

Jason

**Comment by mreiferson** [comment]
> Q1 - With respect to this (0.3.7 and 1.0.4) versioning scheme for go-nsq, are these versions only with respect to go-nsq, and independent of the nsq version?

Yes, those are independent `go-nsq` versions.

> Q2 - Does the go-nsq version with the refactored 1.0.4 API require a particular matched version of nsq to run against? Do I need to be running against a partciular minimum version of nsq?

No, the protocol hasn't changed (sans for some relatively minor _additions_) so `go-nsq` should be compatible dating back into the NSQ `v0.2.x` and on.

> Q3 - Are the HEAD of the git repos for nsq and go-nsq in sync with each other? e.g. if I submit a PR against one, should I be checking it against the other as of the latest code.

NSQ explicitly specifies a [`go-nsq` commit to pin to](https://github.com/nsqio/nsq/blob/master/Godeps#L3).

**Comment by glycerine** [comment]
Thanks Matt.
