### ISSUE TITLE
is producer thread safe when being used by multiple goroutine?

### ISSUE THREAD

**Issue by FlamingTree** [nsqio/go-nsq#165]
As title. And I cannot understand this code snippet: https://github.com/nsqio/go-nsq/blob/master/producer.go#L318-L321, is first send command first get reponse or error, otherwise how to popTransaction guarantee data is poped transaction's response. thanks ~

**Comment by mreiferson** [comment]
Yes, it is goroutine safe.  You're guaranteed to get responses in the order which commands were sent.
