### ISSUE TITLE
advice / question:  exposing over HTTPS to browser / apps

### ISSUE THREAD

**Issue by joeblew99** [nsqio/go-nsq#166]
i am using NSQ for communication between different micro services. The micro services do not have a HTTP transport at all.

So, i am looking for options to help with putting a layer on top of the micro services that supports HTTP and WS (Web Sockets).

There are many possible ways to do it, and i am not quite qure which is the best.

**Comment by mreiferson** [comment]
Hi @joeblew99 this is probably a better conversation for the mailing list and I think we've already got a thread going there.

(going to close, but thanks for your question!)
