### ISSUE TITLE
Question: Reason for returning `error` from nsq.HandlerFunc?

### ISSUE THREAD

**Issue by harlow** [nsqio/go-nsq#167]
Hi, I was wondering what the case would be for returning an `error` from `nsq.HandlerFunc`?
https://github.com/nsqio/go-nsq/blob/master/consumer.go#L38

It deviates slightly from the signature of `http.HandlerFunc`:
https://golang.org/src/net/http/server.go?s=41267:41314#L1408

I'm adding some middlewares to decorate the final message handler with some additional functionality. It works fine but feels a bit weird having unused error as in handler. Should I be using this `error` for a certain use case?

```go
func metricsHandler(next nsq.Handler) nsq.Handler {
	return nsq.HandlerFunc(func(msg *nsq.Message) error {
		fmt.Println("Push to DataDog, Librato, etc")
		next.HandleMessage(msg)
		return nil // deviates from http.Handler signature
	})
}

func finalHandler(msg *nsq.Message) error {
	fmt.Println(string(msg.Body))
	return nil  // deviates from http.Handler signature
}

func main() {
  // ...
  var h nsq.Handler
  h = nsq.HandlerFunc(finalHandler)
  h = metricsHandler(h)
  q.AddHandler(h)
  // ...
}
```

**Comment by mreiferson** [comment]
It's not intended to be compatible with `http.HandlerFunc`, it's documented that way to say that it was designed _in the spirit of_ that standard type.

The `error` in an NSQ message handler is to signify to `go-nsq` whether or not message processing was successful, so that it knows to `REQ` or `FIN` the message.

**Comment by harlow** [comment]
sounds good. thanks for the detailed response.

**Comment by mreiferson** [comment]
@harlow np, there are other ways to respond to the message - you can [`msg.DisableAutoResponse()`](https://godoc.org/github.com/nsqio/go-nsq#Message.DisableAutoResponse) and then call `msg.Finish()` or `msg.Requeue()` explicitly, in which case the error code is essentially meaningless.
