### ISSUE TITLE
consumer can not be received the message in real time  from the nsqds that have the same topic 

### ISSUE THREAD

**Issue by celeskyking** [nsqio/go-nsq#173]
If there are two NSQD that have the same topic, and at the same time to send different messages to the topic, consumer can only be received message from one producer, received from another one only occurs when the querying the lookupd.

**Comment by jehiah** [comment]
@celeskyking nsq consumers are designed to keep persistent connections open to **all** nsqd nodes that have the topic they are interested in.

To receive more than one message concurrently aka "real time" (ie: so you can get one message at a time from each of two nsqd nodes in your case) you would adjust the consumer setting for `Max In Flight`.

**Comment by celeskyking** [comment]
@jehiah  Thanks,  it worked.
