### ISSUE TITLE
consumer receive duplicate message when producer use multiple publish

### ISSUE THREAD

**Issue by wangxingge** [nsqio/go-nsq#180]
I use multiple publish function to publish data each batch has 100 data.

My consumer found there are money duplicate data when receive data from nsqd.

Is there an known issue?

**Comment by mreiferson** [comment]
Under normal operation, there shouldn't be duplicate messages. Did the channel requeue any messages? If so, those would represent duplicates.

**Comment by wangxingge** [comment]
There is no requeue message, I check it on nsq_admin.
I review the code and I confuse that I think that should be work.

I'll test it again and provide more test data and code sample.

Thanks for your help, mreiferson.
