### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by moxar** [nsqio/go-nsq#181]
Hello, 

Do you intend to release a new tag soon on gopkg.in ? I depend on the newly exposed `Producer.DeferredPublish()` method  (#162) and I'd rather use gopkg.in than a local vendoring system.

Best regards

**Comment by mreiferson** [comment]
Yes, we're overdue for a release

I'll try to find some time this weekend to stamp the next stable.

Thanks!

**Comment by mreiferson** [comment]
https://github.com/nsqio/go-nsq/releases/tag/v1.0.6

**Comment by jackluo2012** [comment]
Is the problem solved by golang NSQ delay receiving message? I don't use this on this side. Can you give me an example
