### ISSUE TITLE
which is the memory + disk in http /stats?

### ISSUE THREAD

**Issue by AnotherGoogleFans** [nsqio/go-nsq#186]
I visit the /stats and got the result.
```
nsqd v0.3.8 (built w/go1.6.2)
start_time 2016-08-08T11:16:14+08:00
uptime 6h34m31.342462817s

Health: OK

   [Keywords       ] depth: 0     be-depth: 0     msgs: 2        e2e%: 0.0ns, 0.0ns, 0.0ns
      [test-channel             ] depth: 1     be-depth: 0     inflt: 0    def: 0    re-q: 1     timeout: 1     msgs: 2        e2e%: 0.0ns, 0.0ns, 0.0ns
```

I wonder which one means Disk + memory.  If none, I wonder how to get it. Thank U.
By the way, when I visit the http /stats, the param "&topic=xxxx" and "&channel=xxx" do not work.
And, is there a document to explain which these return value from http stand for?

**Comment by jehiah** [comment]
@AnotherGoogleFans you can use `&format=json` if you want more granular information. `be-depth` is the on-disk depth. 

 If you are looking for general introspection of your cluster I encourage you to use [`nsqadmin`](http://nsq.io/components/nsqadmin.html)

If you can include w/ your output the curl request you are making which shows the topic filtering isn't working that would be helpful. I did a quick check and `topic` and `channel` filtering seem to work fine for me.
