### ISSUE TITLE
How to read from NSQ faster

### ISSUE THREAD

**Issue by AnotherGoogleFans** [nsqio/go-nsq#187]
Hi,
I got a problem with NSQ.
In my project, one program is writing to NSQ, and another(let's called it client) read from NSQ.  The writing program will write 50,000 per second to NSQ. And I found the client read so slow so that the data in NSQ become more and more and finally hard disk get full. In order to checkout which the problem is, I changed the consumer handle to return nil(do nothing, just return nil so that every handle do not use much time), and set NSQ RDY 2,500 and client MaxInFlight 2,000. But it also seemed much slower than the write project.
I wonder how to deal with this problem. Is that any config that I did not noticed?
Here's my Client code:
```
...
	conf := nsq.NewConfig()
	conf.Set("max_in_flight", 2000)
	conf.Set("rdy_redistribute_interval", time.Millisecond*5)
	c, err := nsq.NewConsumer("Keywords", "test-channel", conf)
	if err != nil {
		return fmt.Errorf("fail to create new consumer. Topic: Keywords, channel: test-channel, error: %s", err.Error())
	}
	f := new(f1)
	c.AddHandler(f) // add message handler
	if err := c.ConnectToNSQD("192.168.0.211:4150"); err != nil {
		c.Stop()
		return fmt.Errorf("fail to connect to NSQD. URL: 192.168.0.211:4150, error: %s", err.Error())
	}
...
type f1 struct {
}

func (f *f1) HandleMessage(msg *nsq.Message) error {
	return nil
}



```

**Comment by mreiferson** [comment]
@AnotherGoogleFans typically we would expect _multiple_ consumers subscribed to that topic/channel, but here are a few things to try:

First, add multiple handlers in your consumer using https://godoc.org/github.com/nsqio/go-nsq#Consumer.AddConcurrentHandlers. Also, you can increase the `--max-rdy-count` on `nsqd`, allowing you to also increase the consumer's `max_in_flight` to that value.

Finally, take a look at these config values:

```
// Size of the buffer (in bytes) used by nsqd for buffering writes to this connection
    OutputBufferSize int64 `opt:"output_buffer_size" default:"16384"`
    // Timeout used by nsqd before flushing buffered writes (set to 0 to disable).
    //
    // WARNING: configuring clients with an extremely low
    // (< 25ms) output_buffer_timeout has a significant effect
    // on nsqd CPU usage (particularly with > 50 clients connected).
    OutputBufferTimeout time.Duration `opt:"output_buffer_timeout" default:"250ms"`
```

Keep in mind that consumers have basically 2x the network IO than publishers (they have to `FIN` each message).

**Comment by ploxiln** [comment]
```go
conf.Set("rdy_redistribute_interval", time.Millisecond*5)
```

That's very very low ... if this was ever running on more than one server, they could easily have more than 5ms latency between them at times, particularly if the network links are busy.

**Comment by AnotherGoogleFans** [comment]
Thanks, my problem has been resolved. @mreiferson  @ploxiln

**Comment by andyxning** [comment]
@AnotherGoogleFans which arguments have you adjusted?

**Comment by yunnian** [comment]
同问 最后怎么解决的？

**Comment by pygmalion666** [comment]
Can you share your solution? @AnotherGoogleFan

**Comment by ThreeBearsDan** [comment]
@AnotherGoogleFan I got the same problem. Would mind sharing your solution? Thanks in advanced.

**Comment by ArvonHuang** [comment]
just call message.Finished()
