### ISSUE TITLE
dail nsqd err invalid argument

### ISSUE THREAD

**Issue by whatisgolang** [nsqio/go-nsq#192]
when start consumer log show:
2016/09/06 18:43:46 INF    2 [stat_api_log/ch] (apisstat:4150) connecting to nsqd
2016/09/06 18:43:46 ERR    2 [stat_api_log/ch] (apisstat:4150) error connecting to nsqd - dial tcp 127.0.0.1:0->10.71.32.126:4150: connect: invalid argument

Looking forward to reply thaks

**Comment by mreiferson** [comment]
This part in the log looks odd to me `127.0.0.1:0`, It looks like a misconfiguration of the `Consumer`.

**Comment by whatisgolang** [comment]
@mreiferson 
when donot set LocalAddr  ，all  is ok。log donot show the err.
