### ISSUE TITLE
Document nsqlookupd,nsqadmin configuration file.

### ISSUE THREAD

**Issue by james-lawrence** [nsqio/go-nsq#214]
I had to dig through the code to figure out the following:
1) it used toml syntax.
2) make educated guesses on the keys.

this should be in the documentation with a clear example.

**Comment by jehiah** [comment]
This is relevant to the https://github.com/nsqio/nsq project, not `go-nsq` which is the Go client library.

Please see the example config files here https://github.com/nsqio/nsq/tree/master/contrib
