### ISSUE TITLE
Logger should be configurable

### ISSUE THREAD

**Issue by Soulou** [nsqio/go-nsq#223]
Currently logging is looking like this:

```
 [00] [nsq-consumer(<topic>)]2018/01/12 00:49:08 ERR    6 [tcp_config/default] error querying nsqlookupd (http://172.17.0.1:4161/lookup?topic=<topic>) - got response 404 Not Found "{\"message\":\"TOPIC_NOT_FOUND\"}"
```

And there is no way to change it, shouldn't logging be configurable to fit other practice, a few example:

* Using logrus for key-value logging, and letting one add their own Logger

Or

* Logging callback which could be set by consumer initialization to let the package user handling it their own way?

I think there is something to do, as its currently quite.. poor.

What are your thoughts about that?

**Comment by mreiferson** [comment]
Hi @Soulou, it is possible to adjust the logger with https://godoc.org/github.com/nsqio/go-nsq#Consumer.SetLogger

**Comment by sentient** [comment]
@mreiferson 
It would be be better if the interface gives some better hooks.

Like calldepth is now always 2 (?)

and we have to parse the string to make sense of it (?)

Why not ask for an interface method

LogMessge(int level, string message, map[string] context) error
where r.id, r.topic and r.channel are just entries in the context map.

BTW: also currently you ask for an interface method that returns an error, but you don't handle an error.

It should be. If an error write your native log messge, if no error assume we logged it for you

**Comment by ploxiln** [comment]
The calldepth is correct for where it is used. If your Logger `Output()` were to call another Logger `Output()` you would increment calldepth in between.

It is true that LogLevel is not passed on. So all you can really do is configure the level below which logging is skipped entirely. This is admittedly a deficiency.
