### ISSUE TITLE
hello，I get a mistake when init a producer by http

### ISSUE THREAD

**Issue by fwhezfwhez** [nsqio/go-nsq#230]
it's ok to init by tcp,however http incorrect
```go
package main

import (
	"github.com/nsqio/go-nsq"
	"log"
)
var producer *nsq.Producer
var nsqdAddrTCP = "localhost:4150" //tcp
var nsqdAddrHTTP = "localhost:4151" //http
var nsqAdminAddr = "localhost:4171" //http
var nsqlookupdAddr = "localhost:4161" //http
func init(){
	log.SetFlags(log.Llongfile|log.LstdFlags)
	//init a producer
	var er error
	config := nsq.NewConfig()
	producer,er =nsq.NewProducer(nsqdAddrTCP,config)  //<--ok
	//producer,er = nsq.NewProducer(nsqdHTTP,config)   <--wrong:failed to IDENTIFY - unexpected EOF
        if er!=nil{
		log.Println(er.Error())
		return
	}
	er=producer.Ping()
	if er!=nil{
		log.Println(er.Error())
		return
	}
}
```
so,how to use http as addr

**Comment by ploxiln** [comment]
```go
import (
    "bytes"
    "io/ioutil"
    "net/http"
)

...
buf := bytes.NewReader([]byte(`{"msg": 1234}`)
resp, err := http.Post("http://" + nsqdAddrHTTP + "/pub?topic=test", "application/json", buf)
if err != nil {
	// handle error
}
defer resp.Body.Close()
body, err := ioutil.ReadAll(resp.Body)
...
```

For publishing, you can use any http client. You would only use a Producer for the nsq custom tcp protocol, to be more efficient. In either case, it's not typical to use nsqlookupd for producers, nsqlookupd is typically only used by consumers.

**Comment by fwhezfwhez** [comment]
well.3q

**Comment by victorabarros** [comment]
Hi @ploxiln 

I'm reading your solution and I would like to know if use http client stil better then use go-nsq?
Current the lib have a better performance?
Thanks

**Comment by ploxiln** [comment]
My advice is the same. If you have a service publishing multiple messages per second, performance may be a factor and you may want to use the go-nsq Producer for the custom tcp protocol, instead of plain http.
