### ISSUE TITLE
about tls Two-Way Authentication for nsq

### ISSUE THREAD

**Issue by CuteLilTwo** [nsqio/go-nsq#231]
Thank you for checking my question.
I want to write a demo about tls Two-Way Authentication for nsq.
But When I read the Doc for nsq,I can't understand how to use Two-Way Authentication for nsq because it is too simple to tell me how to deal with this problem.
So can you help me or give me some proposal to deal with this problem?
the last, thank you very much
And this is my email address : lil_aarontoo@163.com

**Comment by ploxiln** [comment]
What exact kind of two-way authentication do you want to do?

To validate that the client used a trusted tls client certificate, use the nsqd option `-tls-root-ca-file` with your own TLS certificate authority cert which you use to sign client certificates (which you also probably created yourself). This is a complicated topic, you'll have to google around for it.

To validate that the client user/password for publishing/consuming a topic/channel, see https://nsq.io/components/nsqd.html#auth

**Comment by SetUpMyYoung** [comment]
oh,thank u very much.But a new question here,I read the Doc and find the IDENTIFY,right?And how to use the IDENTIFY,how to modify the IDENTIFY or the config file?

**Comment by ploxiln** [comment]
For the reader/consumer set `AuthSecret` in the [Config](https://godoc.org/github.com/nsqio/go-nsq#Config) ("Values can be set directly") and it will be included in the `IDENTIFY`

**Comment by SetUpMyYoung** [comment]
Do you have some Communication tool,like WeChat?you can send your account for my email address,and I want to show you my demo and deal with the problem,because so many interface in the nsq,and I can't find what I need.thanks a lot.And in the end ,when I deal my problem I want to collate an interface document for the nsq.It can convenient the people who want to use the nsq
