### ISSUE TITLE
consumer: panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by Huwlsc** [nsqio/go-nsq#232]
Hi, guys. I have meet a unexpected panic in consumer, but I couldn't figure out how it happens.

```
panic: runtime error: makeslice: len out of range

goroutine 327933237 [running]:
github.com/nsqio/go-nsq.ReadResponse(0x111c040, 0xc4224326c0, 0x7774c6, 0xc4203e4300, 0xc4224326c0, 0xc420eefc24, 0x10e)
        /opdData/opdOnline/outFile/rms/compileDeployAgent/current/520/src/github.com/nsqio/go-nsq/protocol.go:60 +0xd4
github.com/nsqio/go-nsq.ReadUnpackedResponse(0x111c040, 0xc4224326c0, 0xc420eefc24, 0x10e, 0x10e, 0x20, 0x0, 0x0)
        /opdData/opdOnline/outFile/rms/compileDeployAgent/current/520/src/github.com/nsqio/go-nsq/protocol.go:91 +0x39
github.com/nsqio/go-nsq.(*Conn).readLoop(0xc4224326c0)
        /opdData/opdOnline/outFile/rms/compileDeployAgent/current/520/src/github.com/nsqio/go-nsq/conn.go:481 +0xae
created by github.com/nsqio/go-nsq.(*Conn).Connect
        /opdData/opdOnline/outFile/rms/compileDeployAgent/current/520/src/github.com/nsqio/go-nsq/conn.go:181 +0x5af
```

ENV
nsqd --version
nsqd v1.0.0-compat (built w/go1.8)

go-nsq version
1.0.5 - 2015-09-19

go version
go version go1.8.4 linux/amd64

**Comment by ploxiln** [comment]
hmm ... that's the `make([]byte, msgSize)` at the end of this block:

```go
	var msgSize int32

	// message size
	err := binary.Read(r, binary.BigEndian, &msgSize)
	if err != nil {
		return nil, err
	}

	// message binary data
	buf := make([]byte, msgSize)
```

I think msgSize must have been a negative number. I wonder if there's also a reasonable upper bound we could enforce here

**Comment by ploxiln** [comment]
(basically caused by some unexpected/corrupted data coming over the tcp connection - maybe due to connecting to the https endpoint and managing get some kind of response, while thinking you were connecting to the nsq-tcp-protocol endpoint...)

**Comment by mreiferson** [comment]
I feel like it's OK to panic for a situation like this given that something must be seriously messed up in the transport chain?
