### ISSUE TITLE
REGISTER command exists or not?

### ISSUE THREAD

**Issue by JoseFMP** [nsqio/go-nsq#241]
In the description of the TCP protocol there is nothing like a `REGISTER` command:
https://nsq.io/clients/tcp_protocol_spec.html

However, the `go-nsq` library has a function to create a `REGISTER` command describing it as being used to register a channel/topic into nsq. `nsq.Register(..., ...)`

Does this command exists or not? 
- If it does not exists, why is it present in `go-nsq` library?
- If it exists, is not working. Nsq complains: `- E_INVALID invalid command REGISTER` what makes sense since this command is not described in the protocol spec.

**Comment by ploxiln** [comment]
`REGISTER` is only used between `nsqd` and `nsqlookupd`, not between consumer clients and nsqd

**Comment by JoseFMP** [comment]
Thank you so much. Clear then.
