### ISSUE TITLE
Is Message.ID unique id ?

### ISSUE THREAD

**Issue by lougxing** [nsqio/go-nsq#250]
````
type Message struct {
	ID        MessageID
        Body []byte
....
}

Is Message.ID global unique id ?  Is it used as a key in map/redis ?

**Comment by mreiferson** [comment]
If your cluster is configured to ensure that `--node-id` for each `nsqd` is unique, then yes, `MessageID` values should be globally unique.

However, I wouldn't rely on this and would recommend you instead include your own identifiers your message bodies that you ensure are globally unique.

**Comment by ploxiln** [comment]
Some further notes:

The nsq MessageID is currently only unique within a topic (and only if nsqd node IDs are different), other topics can easily have a message with the same MessageID.

We only really want to promise that a MessageID will be unique for a particular connection between an nsq consumer and an nsqd. The only use of the MessageID should be for finishing or re-queuing a message. We want to be able to change the way these IDs are generated in the future, to be more efficient, and maybe robust against time going backwards, though I'm not sure if we will ...

**Comment by mreiferson** [comment]
> The nsq MessageID is currently only unique within a topic

Ahh right, forgot about this!

**Comment by lougxing** [comment]
thanks.
