### ISSUE TITLE
last release was Aug 4, 2017

### ISSUE THREAD

**Issue by bpmason1** [nsqio/go-nsq#258]
Are there any plans to create a new release?  I use the semver release tags for pinning my dependencies so I am missing almost 2 years of updates.

**Comment by mreiferson** [comment]
Wow, didn't realize that!

Fortunately, this code base has been pretty stable, there aren't that many changes https://github.com/nsqio/go-nsq/compare/v1.0.7...master

However, the changes that are sitting in `master` touch RDY handling, so I would love some testing to happen before we stamp a stable release.

cc @jehiah @ploxiln
