### ISSUE TITLE
How to create a temporary channel on a topic ?

### ISSUE THREAD

**Issue by Astone-Chou** [nsqio/go-nsq#259]
I was using nsq as a broadcast queue.
I create a topic, then If some worker online, worker will create a personal channel on this topic.
Is there any way to delete the channel when worker offline automatic ?

**Comment by mreiferson** [comment]
Yes, use "ephemeral channels" by naming the channel `name#ephemeral`

**Comment by Astone-Chou** [comment]
thanks very much.
