### ISSUE TITLE
if writeLoop or readLoop is exited,i think the nsq client will not work,why the level of the log in info

### ISSUE THREAD

**Issue by li-bit** [nsqio/go-nsq#272]
c.log(LogLevelInfo, "readLoop exiting")

**Comment by kkxxr66573** [comment]
and i want to know why it must be existed

**Comment by ploxiln** [comment]
This happens when ending the process normally, for example when you stop a service before updating it and starting it again.

**Comment by kkxxr66573** [comment]
sorry,i can not understand,this is the warning log


1 [gradle_job/gradle_job] (100.107.240.206:4150) IO error - EOF
1 [gradle_job/gradle_job] (100.107.240.206:4150) delaying close, 4 outstanding messages
1 [gradle_job/gradle_job] (100.107.240.206:4150) IO error - write tcp 100.108.184.99:54184->100.107.240.206:4150: write: broken pipe
1 [gradle_job/gradle_job] (100.107.240.206:4150) error sending command FIN 0c4414fd3ad36000 - write tcp 100.108.184.99:54184->100.107.240.206:4150: write: broken pipe

**Comment by li-bit** [comment]
Can you change it to not exit?
