### ISSUE TITLE
Does single producer support multi thread ?

### ISSUE THREAD

**Issue by mill888** [nsqio/go-nsq#278]
when we want to produce message to nsq, we connect to nsq by NewProducer(addr,nsq.NewConfig() )， then we can send message to nsq by this producer;

But in real world, the server run in multi threads, and if we want to send message, we had to create a new producer by NewProducer ? Because  in behind of the "NewProducer " , it had to connect to nsq server, and it woud reduce the performance of my server;

So I want to create only one producer when my server start, and in the multi threads of my server, using the producer to send messages again and again.

So, does nsq support this ?

**Comment by ploxiln** [comment]
Yes, the Producer can be used from multiple goroutines running in parallel on different OS threads and cpu cores.

Is the performance "good enough"? Usually, but maybe not always. The limitation would be the channel for transferring commands to the socket writing goroutine, or the socket sending itself. Users with extreme needs can create multiple Producer in a single process, as you have done.
