### ISSUE TITLE
About creating a new producer

### ISSUE THREAD

**Issue by stair-go** [nsqio/go-nsq#280]
Why not provide a 
> NewProducerByLookup (lookupdaddrs [] string, config * config) (* producer, error)

and when the connected nsqd is hung up and then connected to a new nsqd, I think this scenario should be more common~hh

**Comment by stair-go** [comment]
I think the design principle of NSQ is related. For example, if one MSG is sent to another nsqd without the topic, if there are multiple consumers subscribing to it, the message may be lost, but we can provide users with more choices?

**Comment by cocktail18** [comment]
I am puzzled with it too

**Comment by ploxiln** [comment]
Producers should not use nsqlookupd. Consumers use nsqlookupd. Producers might always publish to localhost, or they might publish to a configured pool of nsqd (which might be behind a load balancer, or contacted directly with logic like https://github.com/nsqio/go-nsq/pull/311). Then, consumers user nsqlookupd to find where producers put messages.

**Comment by ploxiln** [comment]
You can find an example of "publish to localhost, consumers use nsqlookupd" near the bottom of this page: https://nsq.io/deployment/topology_patterns.html#distributed-systems
