### ISSUE TITLE
How to: Disconnect client when queue is exhausted

### ISSUE THREAD

**Issue by yohanyflores** [nsqio/go-nsq#286]
I need to disconnect the client when there is no message left. What is the best way to doit?

Ephemeral queue don’t work because I need disk storage.

**Comment by ploxiln** [comment]
(this seems related to https://github.com/nsqio/nsq/issues/1234)

This is not a feature which currently exists. The assumption is that a new message could be published asynchronously.

The only way I can think of, is to periodically make an http request for stats from each nsqd connected, see if the topic/channel is empty, and make the http request to nsqd delete the topic/channel. You would have to implement this manually.

**Comment by ploxiln** [comment]
... and for that to be feasible, we may need to revive https://github.com/nsqio/go-nsq/pull/251

**Comment by ploxiln** [comment]
If you wanted to accomplish this today, here's what I think would be the best way.
Create a service or cron-job which periodically (maybe every 5 minutes):
  * request all nodes from a few nsqlookupd and merge results (use `GET /nodes`)
  * for each node (aka nsqd):
    * request stats (use `GET /stats?format=json&include_clients=0`)
    * for each topic on that node:
      * if topic depth and all channels depth is zero:
        * (optional) wait for 10 second grace period, and check again
        * delete topic (use `POST /topic/delete?topic=name`)

If using nsqlookupd (as is typical), consumers will re-connect to any node (nsqd) which has the topic, creating the channel if necessary. So it won't work to just delete the empty channel. Thus, this only works for whole topics.
