### ISSUE TITLE
You can also write to nsq using http. What are the advantages of go-nsq over the http method

### ISSUE THREAD

**Issue by guonaihong** [nsqio/go-nsq#289]
As the title

**Comment by guonaihong** [comment]
Whether there is pressure test data?

**Comment by ploxiln** [comment]
Using http is convenient, you can use the http request library of any language or framework you want. In many cases it may be quite sufficient for the use case / message rate.

The "binary" protocol is more efficient in terms of both bytes and cpu-time. All the http headers are skipped. The binary protocol message publish is like:

```
PUB <topic-name>\n
<4-bytes-len><N-bytes-body>
```

and the response is like:

```
<4-bytes-len><4-bytes-type>OK
```

That is a lot less work to parse than HTTP headers.

Unfortunately I don't have a good benchmark comparing performance of each method directly ... we have a few benchmarks in our nsqd test suite, but not that in particular, I don't think ...
