### ISSUE TITLE
why "connectedFlag" not set zero when Stop() called

### ISSUE THREAD

**Issue by TT6033** [nsqio/go-nsq#291]
connectedFlag =1 when  ConnectToNSQLookupd called
why "connectedFlag" not set zero when Stop() called?

**Comment by ploxiln** [comment]
... just because it wasn't needed. It is only used in one place, to ensure that handlers are not added after starting connections:

```go
func (r *Consumer) AddConcurrentHandlers(handler Handler, concurrency int) {
	if atomic.LoadInt32(&r.connectedFlag) == 1 {
		panic("already connected")
	}
```

It is assumed that after `Stop()` the process will exit, or will create a new Consumer when needed again.

**Comment by TT6033** [comment]
It is only used twice....because some Strange reason.
I think it should be reset when stop the connection
