### ISSUE TITLE
Why there is no possibility to publish to nsq lookupd?

### ISSUE THREAD

**Issue by a-urth** [nsqio/go-nsq#293]
Maybe I'm missing how it works, but why publish for producer accepts only `nsqd` address?

**Comment by jehiah** [comment]
`nsqlookupd`  does not handle messages, those are only handled by `nsqd`.  `nsqlookupd` is just a facilitator to discovering message topology, but it's focused on the consumption side, not on the producer side.

This section of the docs might be helpful for you
https://nsq.io/deployment/topology_patterns.html#distributed-systems

**Comment by a-urth** [comment]
Oh I see. i thought that lookupd serves as discovery for both consumers and producers and it's possible for producer to discover nsqd depending on the topic its pushing into. But my assumption is wrong.
Now it makes more sense. Thank you very much!
