### ISSUE TITLE
Any way to share connections within multiple topics and channels?

### ISSUE THREAD

**Issue by umialpha** [nsqio/go-nsq#299]
From the code, it seems that every time we create a consumer for some topic and channel, it will create connections to nsqd. Is there any way to share the connections?

**Comment by jehiah** [comment]
nsqd does not currently support subscribing to more than one topic/channel on a TCP connection; That is the constraint that limits re-using connections.

**Comment by umialpha** [comment]
Thanks for your reply. The server  seems to treat each connection as a client.
