### ISSUE TITLE
How to manually acknowledge message without nsq.Message context.

### ISSUE THREAD

**Issue by umialpha** [nsqio/go-nsq#300]
### Hi, I have the following scenario.

We have some stateless servers acting as NSQ proxies(not general proxies, but with some application logic), proving gRPC interfaces. Here is our workflow.

1. gRPC client requests a `topic/channel/message` from a load-balanced proxy.
2. proxy (pre)constructs connections to NSQD and (pre)stores some messages locally.
a. it sends the local message to the gRPC client.
b. it stores the message meta data in the `Redis`.
3. When the gRPC finishes the message, it acknowledges the message to the load-balanced proxies.
4. the proxy checks the message from `Redis`, if it is valid, it will send a FIN COMMAND to the NSQ.

### My Question

**is there any high-level API to manually acknowledge a message only with its `topic`, `channel`, `messageID` and other metadatas.**

### Why we need such a proxies:
1. We have a lot of clients( about 10k), but one message usually takes seconds even minutes to finish.  It may be a concern for NSQ to hold so many connections. So we use proxies to share the load.
2. We need some logic in the proxies.

**Comment by ploxiln** [comment]
No, this is not an intended use of the library, or the consumer interface to nsqd. You should only acknowledge a messageID over the consumer connection which delivered that messageID.

**Comment by ploxiln** [comment]
Some more details: when you connect to nsqd, that connection gets a `clientID` which the client cannot control:

```go
func (p *protocolV2) IOLoop(conn net.Conn) error {
	var err error
	var line []byte
	var zeroTime time.Time

	clientID := atomic.AddInt64(&p.ctx.nsqd.clientIDSequence, 1)
	client := newClientV2(clientID, conn, p.ctx)
```

When you acknowledge a message, it ends up in this method:

```go
func (c *Channel) FinishMessage(clientID int64, id MessageID) error {
	msg, err := c.popInFlightMessage(clientID, id)
```

and that verifies that this is the exact connection which the message was delivered to:

```go
func (c *Channel) popInFlightMessage(clientID int64, id MessageID) (*Message, error) {
	c.inFlightMutex.Lock()
	msg, ok := c.inFlightMessages[id]
	if !ok {
		c.inFlightMutex.Unlock()
		return nil, errors.New("ID not in flight")
	}
	if msg.clientID != clientID {
		c.inFlightMutex.Unlock()
		return nil, errors.New("client does not own message")
	}
```

So, you'll need to keep the same connection from the same service process that received the message, in order to be able to acknowledge the message. So you can easily keep the `nsq.Message` in memory along side that.

**Comment by umialpha** [comment]
Thanks for your reply. It helps for my design
