### ISSUE TITLE
failed to read command read tcp i/o timeout

### ISSUE THREAD

**Issue by pengbinbin1** [nsqio/go-nsq#303]
i used go-nsq  to make a consuemer ,and the progorm has working fine for some days.but yesterday ,it stop working,even though i have not changed anything.It looks like the consumer has stoped, but you can see the message is still pushed into the topic on nsqadmin ,and nsqd's log show like this :failed to read command - read tcp 172.28.0.10:4150-\u003e172.28.0.20:53756: i/o timeout.

**Comment by ploxiln** [comment]
The consumer process is supposed to reconnect in this case. Perhaps your network or setup has made this impossible, or perhaps there is a bug in go-nsq. We cannot debug this given the information you have provided. If you can debug the issue, and propose and explain a fix, that would be helpful.
