### ISSUE TITLE
will consumer reconnect to the server when the connection is closed by server?

### ISSUE THREAD

**Issue by pengbinbin1** [nsqio/go-nsq#304]
will consumer reconnect to the server when the connection is closed by server? and how to set the reconnect times ?

**Comment by ploxiln** [comment]
If you use `ConnectToNSQLookupd()` or `ConnectToNSQLookupds()`, then yes, the Consumer will reconnect. The period for checking for new or no-longer-connected nsqd is controlled by `LookupdPollInterval` in the [Config](https://godoc.org/github.com/nsqio/go-nsq#Config)

**Comment by pengbinbin1** [comment]
@ploxiln  thank you very much
