### ISSUE TITLE
docs: what address in `func NewProducer(addr string, ...)`?

### ISSUE THREAD

**Issue by golopot** [nsqio/go-nsq#309]
I just learnt nsq yesterday. I have a problem when I use the function `NewProducer(addr, config)`: Which address should I use, the `nsqdlookupd` one or the `nsqd` one?

```go
// NewProducer returns an instance of Producer for the specified address
// ...
func NewProducer(addr string, config *Config) (*Producer, error) {
```

**Comment by ploxiln** [comment]
`addr` is a single _nsqd_ tcp address (yes, the docs should be clearer about that)
