### ISSUE TITLE
panic: send closed channel -  incomingMessages

### ISSUE THREAD

**Issue by Allenxuxu** [nsqio/go-nsq#325]
https://github.com/nsqio/go-nsq/blob/2a2babe56732d309086255f45e60617fd8683ede/consumer.go#L767

In extreme case, before  it is successful, consumer has been stop. 
It may lead to panic. Because of 

```
func (r *Consumer) stopHandlers() {
	r.stopHandler.Do(func() {
		r.log(LogLevelInfo, "stopping handlers")
		close(r.incomingMessages)
	})
}
```

**Comment by mreiferson** [comment]
see #326
