### ISSUE TITLE
How to use Command?

### ISSUE THREAD

**Issue by caitou2019** [nsqio/go-nsq#335]
I want to delete the channel under topic. Although I found the command to create and delete topic / channel, the command cannot be executed. How should I perform the operation? Thank u !!!

This is the source code for creating and deleting commands:

nsq.UnRegister

// UnRegister creates a new Command to remove a topic/channel for the connected nsqd
func UnRegister(topic string, channel string) *Command {
	params := [][]byte{[]byte(topic)}
	if len(channel) > 0 {
		params = append(params, []byte(channel))
	}
	return &Command{[]byte("UNREGISTER"), params, nil}
}

**Comment by ploxiln** [comment]
The "UNREGISTER" command is only understood by nsqlookupd.

To delete topics and channels, you should use the nsqd http api (for single nsqd at a time), or nsqlookupd http api (for cluster-wide).
https://nsq.io/components/nsqd.html#post-topicdelete
https://nsq.io/components/nsqd.html#post-channeldelete
https://nsq.io/components/nsqlookupd.html#post-topicdelete
https://nsq.io/components/nsqlookupd.html#post-channeldelete

This go-nsq library is also used internally by nsqd/nsqlookupd so some parts aren't really useful for normal nsq client apps.
