### ISSUE TITLE
"go test" fails with "connection refused"

### ISSUE THREAD

**Issue by saurabhghumnar** [nsqio/go-nsq#343]
I am working on the go-nsq package and I have been testing it. I get the error mentioned error in the title and I am unable to figure out its cause.

Package version : v1.0.8
Langauge: Go
Golang version : 1.16
System : linux/ppc64le

Command used : **go test ./...**  (inside the cloned package)

Error snap :
[root@310a353aef06 go-nsq@v1.0.8]# go test ./...
--- FAIL: TestConsumer (0.00s)
    mock_test.go:25: DBG    1 [rdr_test1638945077/ch] starting Handler
    consumer_test.go:63: Post "http://127.0.0.1:4151/pub?topic=rdr_test1638945077": dial tcp 127.0.0.1:4151: connect: connection refused
--- FAIL: TestConsumerTLS (0.00s)
    mock_test.go:25: DBG    2 [rdr_test_tls1638945077/ch] starting Handler
    consumer_test.go:63: Post "http://127.0.0.1:4151/pub?topic=rdr_test_tls1638945077": dial tcp 127.0.0.1:4151: connect: connection refused
--- FAIL: TestConsumerDeflate (0.00s)
    mock_test.go:25: DBG    3 [rdr_test_deflate1638945077/ch] starting Handler
    consumer_test.go:63: Post "http://127.0.0.1:4151/pub?topic=rdr_test_deflate1638945077": dial tcp 127.0.0.1:4151: connect: connection refused
--- FAIL: TestConsumerSnappy (0.00s)
    mock_test.go:25: DBG    4 [rdr_test_snappy1638945077/ch] starting Handler
    consumer_test.go:63: Post "http://127.0.0.1:4151/pub?topic=rdr_test_snappy1638945077": dial tcp 127.0.0.1:4151: connect: connection refused
--- FAIL: TestConsumerTLSDeflate (0.00s)
    mock_test.go:25: DBG    5 [rdr_test_deflate_tls1638945077/ch] starting Handler
    consumer_test.go:63: Post "http://127.0.0.1:4151/pub?topic=rdr_test_deflate_tls1638945077": dial tcp 127.0.0.1:4151: connect: connection refused
--- FAIL: TestConsumerTLSSnappy (0.00s)
    mock_test.go:25: DBG    6 [rdr_test_snappy_tls1638945077/ch] starting Handler
    consumer_test.go:63: Post "http://127.0.0.1:4151/pub?topic=rdr_test_snappy_tls1638945077": dial tcp 127.0.0.1:4151: connect: connection refused
--- FAIL: TestConsumerTLSClientCert (0.00s)
    mock_test.go:25: DBG    7 [rdr_test_tls1638945077/ch] starting Handler
    consumer_test.go:63: Post "http://127.0.0.1:4151/pub?topic=rdr_test_tls1638945077": dial tcp 127.0.0.1:4151: connect: connection refused
--- FAIL: TestConsumerTLSClientCertViaSet (0.00s)
    mock_test.go:25: DBG    8 [rdr_test_tls1638945077/ch] starting Handler
    consumer_test.go:63: Post "http://127.0.0.1:4151/pub?topic=rdr_test_tls1638945077": dial tcp 127.0.0.1:4151: connect: connection refused
--- FAIL: TestProducerConnection (0.00s)
    producer_test.go:53: should lazily connect - dial tcp 127.0.0.1:0->127.0.0.1:4150: connect: connection refused
--- FAIL: TestProducerPing (0.00s)
    producer_test.go:75: should connect on ping
--- FAIL: TestProducerPublish (0.00s)
    producer_test.go:98: error dial tcp 127.0.0.1:4150: connect: connection refused
--- FAIL: TestProducerMultiPublish (0.00s)
    producer_test.go:126: error dial tcp 127.0.0.1:4150: connect: connection refused
--- FAIL: TestProducerPublishAsync (0.00s)
    producer_test.go:150: dial tcp 127.0.0.1:4150: connect: connection refused
--- FAIL: TestProducerMultiPublishAsync (0.00s)
    producer_test.go:189: dial tcp 127.0.0.1:4150: connect: connection refused
--- FAIL: TestProducerHeartbeat (0.00s)
    producer_test.go:226: wrong error - dial tcp 127.0.0.1:4150: connect: connection refused
FAIL
FAIL    github.com/nsqio/go-nsq 1.680s
FAIL

Any pointers will be helpful to resolve this issue.
Thanks

**Comment by ploxiln** [comment]
It's a bit unconventional, but ... you have to run `./test.sh`, that will find `nsqd` and `nsqlookupd` in your `PATH`, and run them in the background to support the go tests.

**Comment by saurabhghumnar** [comment]
Thanks for the quick solution. So I tried the ./test.sh in the go-nsq package and all the tests pass perfectly. I guess testing the tests separately using commands like go test ./... only will create errors as nsqd won't be running then
