### ISSUE TITLE
MaxAttempts Callback

### ISSUE THREAD

**Issue by dhulihan** [nsqio/go-nsq#359]
When a message hits max attempts, we currently log that we're giving up, then we FIN the message.

https://github.com/nsqio/go-nsq/blob/c2c38427f2953526654f16e079c50f5262d64a7d/consumer.go#L1174

It would be nice to have support a configurable callback func, to give the consumer more flexibility to handle messages that have hit max attempts.

https://nsq.io/clients/building_client_libraries.html#message-handling

> Finally, a property of each message is the number of attempts. Client libraries should compare this value against the configured max and discard messages that have exceeded it. When a message is discarded there should be a callback fired. Typical default implementations of this callback might include writing to a directory on disk, logging, etc. The user should be able to override the default handling.

**Comment by mreiferson** [comment]
This is already possible via: https://pkg.go.dev/github.com/nsqio/go-nsq#FailedMessageLogger
