### ISSUE TITLE
producer.PublishAsync - Not working as expected

### ISSUE THREAD

**Issue by wlbwlbwlb** [nsqio/go-nsq#370]
I posted 10,000 messages but only processed 7,368 of them

```
        count := 10000
	for i := 0; i < count; i++ {
		messageBody := []byte("hello")
		topicName := "topic7"
		err = producer.PublishAsync(topicName, messageBody, nil)
		if err != nil {
			fmt.Println(err)
		}
	}
```

![image](https://github.com/user-attachments/assets/10d322a8-6cb9-4737-b0d1-3957a083ccea)

**Comment by mreiferson** [comment]
Going to need more logs to figure out what your consumers are doing, but my guess would be they're not `FIN` (finishing) the messages and thus are "stuck" because `nsqd` won't send them any more messages.
