### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by virtuallynathan** [nsqio/go-nsq#66]
Hey there,
I'm using this code to make a producer that sends messages to NSQ. I'm using 
PublishAsync(), with a "responder" that basically does nothing:

``` go
var respChan chan *nsq.ProducerTransaction

func responder(respChan chan *nsq.ProducerTransaction) {
    for _ = range respChan {
        //Get rid of the messages or something... should probably respond, but not sure
        //how to do that yet...
    }
}
```

I'm sending as many messages as possible, calling publishAsync() in a loop reading from memory. My code maxes out the CPU, and manages about 14,000 messages per second (the messages are quite small, a msgpack'd struct containing a < 16 char string). 

In doing a code profile, my code apparently spends 50.5% of its time in "ExternalCode" (no idea what that is).

I've attached my code profile:
![cpu copy](https://cloud.githubusercontent.com/assets/3472173/3633289/e14b8a96-0edb-11e4-86e0-24bdd2026aa6.png)

Any idea what is going on here?

**Comment by kofj** [comment]
Is there any endless loop in your code?
