### ISSUE TITLE
consumer: retry nsqlookupd query if it fails

### ISSUE THREAD

**Issue by mnutt** [nsqio/go-nsq#97]
A few days ago, due to a provisioning error, I accidentally added a bad lookupd to the list.  My app eventually queried a working lookupd and began processing messages, but it took about a minute. (which is what the poll interval is set to)  I know there is a balance between finding new nodes and not overloading the lookupds, but would it make sense to try all of the lookupds on startup until one returned success? I'm happy to submit a pull request if that's the case.

**Comment by mreiferson** [comment]
see #209
